cms/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from cms import views


urlpatterns = patterns(
    '',
    url(r'^book/$', views.book_list, name='book_list'),
    url(r'^book/add/$', views.book_edit, name='book_add'),
    url(r'^book/mod/(?P<book_id>\d+)$', views.book_edit, name='book_mod'),
    url(r'^book/del/(?P<book_id>\d+)$', views.book_del, name='book_del'),
    url(r'^impression/(?P<book_id>\d+)/$', views.ImpressionList.as_view(), name='impression_list'),
    url(r'^impression/add/(?P<book_id>\d+)/$', views.impression_edit, name='impression_add'),
    url(r'^impression/mod/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_edit, name='impression_mod'),
    url(r'^impression/del/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_del, name='impression_del'),
)

myboard/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
        '',
        url('', include('django_socketio.urls')),
        url('', include('websock.urls')),
        url(r'^admin/', include(admin.site.urls)),
        url(r'^cms/', include('cms.urls', namespace='cms')),
        url(r'^simpleboard/', include('simpleboard.urls', namespace='simpleboard')),
)

simpleboard/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from simpleboard import views
import django.contrib.auth.views


urlpatterns = patterns(
        '',
        url(r'^$', views.top, name='top'),
        url(r'^boards/$', views.board_list, name='board_list'),
        url(r'^board/new/$', views.board_new, name='board_new'),
        url(r'^board/(?P<board_id>\d+)/$', views.board_show, name='board_show'),
        url(r'^board/(?P<board_id>\d+)/post/new/$', views.post_new, name='post_new'),
        url(r'^users/new/$', views.user_new, name='user_new'),
        url(r'^login/$', django.contrib.auth.views.login, {'template_name': 'simpleboard/user_login.html'}),
        url(r'^logout/$', django.contrib.auth.views.logout, {'template_name': 'simpleboard/user_loggedout.html',}),
        url(r'^favorite/$', views.add_favorite, name='add_favorite'),
)

simpleboard/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class Board(models.Model):
    title = models.CharField(u'Title', max_length=255)

    def __unicode__(self):
        return unicode(self.title) or u''


class Post(models.Model):
    comment = models.TextField(u'Content')
    board = models.ForeignKey(Board, verbose_name=u'Board', related_name='posts')
    user = models.ForeignKey(User, verbose_name=u'User', related_name='posts')

    def __unicode__(self):
        return unicode(self.comment) or u''


class Favorite(models.Model):
    post = models.ForeignKey(Post, verbose_name='Post', related_name='favorites')
    user = models.ForeignKey(User, verbose_name='User', related_name='favorites')

    def __unicode__(self):
        return unicode(self.post) or u''

    def unq_validation(self):
        if Favorite.objects.filter(post=self.post, user=self.user):
            raise ValidationError
        return True

simpleboard/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from simpleboard.models import Board, Post


class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ('title',)


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('comment',)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', )

simpleboard/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from simpleboard.models import Board, Post, Favorite
from simpleboard.forms import BoardForm, PostForm, CustomUserCreationForm
import json


LOGIN_URL = '/simpleboard/login/'

LOGIN_REDIRECT_URL = '/simpleboard/'


def top(request):
    return render_to_response(
        'simpleboard/top.html',
            {},
        context_instance=RequestContext(request)
    )


def user_new(request):
    user = User()
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, instance=user)
        if form.is_valid():
            form.save(commit=True)
            return redirect('simpleboard:board_list')

    return render_to_response(
        'simpleboard/user_new.html',
            {'form': form},
        context_instance=RequestContext(request)
    )


@login_required
def board_list(request):
    boards = Board.objects.all().order_by('title')
    board = Board()
    form = BoardForm(instance=board)
    return render_to_response(
        'simpleboard/board_list.html',
        {'boards': boards, 'form': form},
        context_instance=RequestContext(request)
    )


@login_required
def board_show(request, board_id):
    faved_post_ids = map(int, request.user.favorites.values_list('post_id', flat=True))
    board = get_object_or_404(Board, pk=board_id)
    posts = board.posts.all().prefetch_related('user__favorites__post').order_by('-id')
    post = Post()
    form = PostForm(instance=post)
    return render_to_response(
        'simpleboard/board_show.html',
            {'board': board, 'posts': posts, 'form': form, 'faved_id': faved_post_ids},
        context_instance=RequestContext(request)
    )


@login_required
def board_new(request):
    board = Board()
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.save()
            return redirect('simpleboard:board_list')
    else:
        form = BoardForm(instance=board)

    return render_to_response(
        'simpleboard/board_new.html',
        dict(form=form),
        context_instance=RequestContext(request)
    )


@login_required
def post_new(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    post = Post()

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.board_id = board.id
            post.user_id = request.user.id
            post.save()
            return redirect('simpleboard:board_show', board_id=board_id)
    else:
        form = PostForm(instance=post)

    return render_to_response(
        'simpleboard/post_new.html',
            {'form': form, 'board': board},
        context_instance=RequestContext(request)
    )


@login_required
def add_favorite(request):
    from django.http import Http404
    current_user = request.user
    if request.method == 'POST':
        req_data = json.loads(request.body)
        post_id = req_data['post_id']
        fav = Favorite(user_id=current_user.id, post_id=post_id)
        if fav.unq_validation():
            fav.save()
            res = {
                'status': 200,
                'message': 'Successfully favorited!!'
            }
        else:
            res = {
                'status': 302,
                'message': 'You already favs it!'
            }
        return JsonResponse(res)
    else:
        raise Http404

simpleboard/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Simple Board {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrahead %} {% endblock %}
</head>
<body>
<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>
</body>
</html>

simpleboard/templates/sb_base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Simple Board {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extrahead %} {% endblock %}
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
    <div class="navbar-header">
         <a class="navbar-brand" href="{% url 'simpleboard:top' %}">SimpleBoard</a>
    </div>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'simpleboard:board_list' %}">Boards</a></li>
                <li><a href="/simpleboard/logout">Log Out</a></li>
            {% else %}
                <li><a href="/simpleboard/login">Log In</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>
</body>
</html>